packages:
  - apps/*
  - packages/*
  - playgrounds/*

catalog:
  '@antfu/eslint-config': ^4.15.0
  '@ctrl/tinycolor': ^4.1.0
  '@hebilicious/vue-query-nuxt': ^0.3.0
  '@iconify-json/prime': ^1.2.2
  '@iconify/utils': ^2.3.0
  '@nuxt/devtools': ^2.5.0
  '@nuxt/eslint': ^1.4.1
  '@nuxt/fonts': ^0.11.4
  '@nuxt/icon': ^1.14.0
  '@nuxt/schema': ^3.17.5
  '@nuxtjs/color-mode': ^3.5.2
  '@pinia/nuxt': ^0.11.1
  '@primevue/nuxt-module': ^4.3.5
  '@primevue/themes': ^4.3.5
  '@tanstack/vue-query': ^5.80.7
  '@tanstack/vue-query-devtools': ^5.80.7
  '@types/nprogress': ^0.2.3
  '@unocss/eslint-plugin': ^66.2.3
  '@unocss/nuxt': ^66.2.3
  '@unocss/reset': ^66.2.3
  '@vee-validate/nuxt': ^4.15.1
  '@vee-validate/zod': ^4.15.1
  '@vite-pwa/nuxt': ^1.0.4
  '@vitest/coverage-v8': ^3.2.4
  '@vueuse/core': ^13.3.0
  '@vueuse/motion': ^3.0.3
  '@vueuse/nuxt': ^13.3.0
  axios: ^1.10.0
  chart.js: ^4.5.0
  consola: ^3.4.2
  date-fns: ^4.1.0
  defu: ^6.1.4
  es-toolkit: ^1.39.3
  eslint: ^9.29.0
  eslint-flat-config-utils: ^2.1.0
  eslint-plugin-format: ^1.0.1
  filepond: ^4.32.8
  filepond-plugin-file-rename: ^1.1.8
  filepond-plugin-file-validate-type: ^1.2.9
  filepond-plugin-image-preview: ^4.6.12
  husky: ^9.1.7
  jiti: ^2.4.2
  json-editor-vue: ^0.18.1
  lint-staged: ^16.1.2
  lossless-json: ^4.1.0
  nprogress: ^0.2.0
  nuxt: ^3.17.5
  nuxt-html-inject-commands: ^0.1.3
  pausable-timers: ^0.2.0
  pinia: ^3.0.3
  postcss-preset-env: ^10.2.3
  primevue: ^4.3.5
  type-fest: ^4.41.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.2.3
  vanilla-jsoneditor: ^3.6.0
  vee-validate: ^4.15.1
  vitepress: ^1.6.3
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-component-type-helpers: ^2.2.10
  vue-filepond: ^7.0.4
  vue-tsc: ^2.2.10
  worker-timers: ^8.0.22
  zod: ^3.25.67
