packages:
  - apps/*
  - packages/*
  - playgrounds/*

catalog:

catalogs:
  build:
    jiti: ^2.5.1
    postcss-preset-env: ^10.2.4
    tsdown: ^0.13.4
    vite: npm:rolldown-vite@latest
  deps:
    '@ctrl/tinycolor': ^4.1.0
    axios: ^1.11.0
    consola: ^3.4.2
    date-fns: ^4.1.0
    defu: ^6.1.4
    lossless-json: ^4.1.1
    pausable-timers: ^0.2.0
    worker-timers: ^8.0.23
    zod: ^4.0.15
  dev:
    '@nuxt/devtools': ^2.6.2
    '@tanstack/vue-query-devtools': ^5.84.0
    '@vue/tsconfig': ^0.7.0
    eslint-flat-config-utils: ^2.1.1
    typescript: ^5.9.2
    unplugin-auto-import: ^20.0.0
    vue-tsc: ^3.0.5
  docs:
    vitepress: ^1.6.4
  frontend:
    '@unocss/reset': ^66.4.2
    chart.js: ^4.5.0
    filepond: ^4.32.8
    filepond-plugin-file-rename: ^1.1.8
    filepond-plugin-file-validate-type: ^1.2.9
    filepond-plugin-image-preview: ^4.6.12
    nprogress: ^0.2.0
    unocss: ^66.4.2
    vanilla-jsoneditor: ^3.8.0
  frontend-nuxt:
    '@hebilicious/vue-query-nuxt': ^0.3.0
    '@nuxt/fonts': ^0.11.4
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/seo': ^3.1.0
    '@pinia/nuxt': ^0.11.2
    '@primevue/nuxt-module': ^4.3.7
    '@unocss/nuxt': ^66.4.2
    '@vee-validate/nuxt': ^4.15.1
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.6.0
    nuxt: ^4.0.3
    nuxt-html-inject-commands: ^0.1.3
  frontend-vue:
    '@primevue/themes': ^4.3.7
    '@tanstack/vue-query': ^5.83.1
    '@vee-validate/zod': ^4.15.1
    '@vueuse/core': ^13.6.0
    '@vueuse/motion': ^3.0.3
    json-editor-vue: ^0.18.1
    pinia: ^3.0.3
    primevue: ^4.3.7
    vee-validate: ^4.15.1
    vue: ^3.5.18
    vue-filepond: ^7.0.4
  icons:
    '@iconify-json/carbon': ^1.2.11
    '@iconify-json/prime': ^1.2.2
    '@iconify/utils': ^3.0.0
    '@nuxt/icon': ^1.15.0
  inline:
    es-toolkit: ^1.39.8
  lint:
    '@antfu/eslint-config': ^5.2.0
    '@nuxt/eslint': ^1.8.0
    '@unocss/eslint-plugin': ^66.4.2
    eslint: ^9.32.0
    eslint-plugin-format: ^1.0.1
    husky: ^9.1.7
    lint-staged: ^16.1.4
  test:
    '@vitest/coverage-v8': ^3.2.4
    vitest: ^3.2.4
  types:
    '@nuxt/schema': ^4.0.3
    '@types/node': ^24.2.0
    '@types/nprogress': ^0.2.3
    type-fest: ^4.41.0
    vue-component-type-helpers: ^3.0.5
