/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimationFrameMock: typeof import('./../components/AnimationFrameMock.vue')['default']
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppLogos: typeof import('./../components/AppLogos.vue')['default']
    HiCounter: typeof import('./../components/HiCounter.vue')['default']
    InputEntry: typeof import('./../components/InputEntry.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
  }
}
