/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/example': RouteRecordInfo<'/example', '/example', Record<never, never>, Record<never, never>>,
    '/example/alias': RouteRecordInfo<'/example/alias', '/example/alias', Record<never, never>, Record<never, never>>,
    '/example/console': RouteRecordInfo<'/example/console', '/example/console', Record<never, never>, Record<never, never>>,
    '/example/naive': RouteRecordInfo<'/example/naive', '/example/naive', Record<never, never>, Record<never, never>>,
    '/example/naive/': RouteRecordInfo<'/example/naive/', '/example/naive', Record<never, never>, Record<never, never>>,
    '/example/query': RouteRecordInfo<'/example/query', '/example/query', Record<never, never>, Record<never, never>>,
    '/example/query/cancel': RouteRecordInfo<'/example/query/cancel', '/example/query/cancel', Record<never, never>, Record<never, never>>,
    '/example/query/combined': RouteRecordInfo<'/example/query/combined', '/example/query/combined', Record<never, never>, Record<never, never>>,
    '/example/query/infinite': RouteRecordInfo<'/example/query/infinite', '/example/query/infinite', Record<never, never>, Record<never, never>>,
    '/example/query/mutation': RouteRecordInfo<'/example/query/mutation', '/example/query/mutation', Record<never, never>, Record<never, never>>,
    '/example/query/query': RouteRecordInfo<'/example/query/query', '/example/query/query', Record<never, never>, Record<never, never>>,
    '/example/request': RouteRecordInfo<'/example/request', '/example/request', Record<never, never>, Record<never, never>>,
    '/example/shared': RouteRecordInfo<'/example/shared', '/example/shared', Record<never, never>, Record<never, never>>,
    '/example/store': RouteRecordInfo<'/example/store', '/example/store', Record<never, never>, Record<never, never>>,
    '/example/unocss': RouteRecordInfo<'/example/unocss', '/example/unocss', Record<never, never>, Record<never, never>>,
    '/example/vueuse': RouteRecordInfo<'/example/vueuse', '/example/vueuse', Record<never, never>, Record<never, never>>,
  }
}
