/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/example': RouteRecordInfo<'/example', '/example', Record<never, never>, Record<never, never>>,
    '/example/alias': RouteRecordInfo<'/example/alias', '/example/alias', Record<never, never>, Record<never, never>>,
    '/example/console': RouteRecordInfo<'/example/console', '/example/console', Record<never, never>, Record<never, never>>,
    '/example/shared': RouteRecordInfo<'/example/shared', '/example/shared', Record<never, never>, Record<never, never>>,
    '/example/store': RouteRecordInfo<'/example/store', '/example/store', Record<never, never>, Record<never, never>>,
    '/example/vueuse': RouteRecordInfo<'/example/vueuse', '/example/vueuse', Record<never, never>, Record<never, never>>,
  }
}
