/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ASpace: typeof import('ant-design-vue/es')['Space']
    BaseSideRoutes: typeof import('./../components/BaseSideRoutes.vue')['default']
    DatePickerEnhanced: typeof import('./../components/DatePicker/DatePickerEnhanced.vue')['default']
    DatePickerrHalfQuarterYear: typeof import('./../components/DatePicker/DatePickerrHalfQuarterYear.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDatePickerPro: typeof import('../components/DatePickerEnhanced.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HalfYearDatePicker: typeof import('./../components/HalfYearDatePicker.vue')['default']
    HomeOutlined: typeof import('@ant-design/icons-vue')['HomeOutlined']
    IEpSearch: typeof import('~icons/ep/search')['default']
    LoadingOutlined: typeof import('@ant-design/icons-vue')['LoadingOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingFilled: typeof import('@ant-design/icons-vue')['SettingFilled']
    SmileOutlined: typeof import('@ant-design/icons-vue')['SmileOutlined']
    SyncOutlined: typeof import('@ant-design/icons-vue')['SyncOutlined']
  }
}
